python: upgrade safety to 2.3.4 (#5658)
we need https://github.com/pyupio/safety/commit/2c4bb4bdb934558396a7274b4109439559bbb201
because linting currently fails with:

ImportError: cannot import name 'LegacyVersion' from 'packaging.version'
 (/home/runner/work/nessie/nessie/python/.tox/lint/lib/python3.8/site-packages/packaging/version.py)